Repository epam/edp-tekton, pull requests merged in 2024-10, with the labels that each got.

#316 feat: Add bitbucket-set-status task for tekton pipelines
  charts/common-library/Chart.yaml
  charts/common-library/README.md
  charts/common-library/templates/_common_bitbucket.yaml
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/tasks/bitbucket-set-status.yaml
Labels: enhancement, feature

#318 feat: Add Support for BitBucket as GitServer (#317)
  README.md
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
  charts/pipelines-library/README.md.gotmpl
  charts/pipelines-library/templates/_helpers.tpl
  charts/pipelines-library/values.yaml
Labels: feature

#319 feat: Add last commit message to interceptor response for BitBucket
  cmd/interceptor/main.go
  go.mod
  go.sum
  pkg/event_processor/bitbucket/bitbucket.go
  pkg/event_processor/bitbucket/bitbucket_test.go
  pkg/event_processor/codebase.go
  pkg/event_processor/event.go
  pkg/event_processor/github/github.go
  pkg/event_processor/github/github_test.go
  pkg/interceptor/edp_interceptor.go
Labels: enhancement

#321 docs: Update changelog file for release notes (#302)
  CHANGELOG.md
Labels: documentation

#278 feat: Add Tekton resources for deploy RPM package via AWX (#277)
  charts/pipelines-library/templates/pipelines/cd/deploy-ansible-awx.yaml
  charts/pipelines-library/templates/tasks/cd/deploy-ansible-awx.yaml
  charts/pipelines-library/templates/triggers/cd/deploy-ansible-awx.yaml
Labels: enhancement

#276 feat: Add resources for deploy rpm(#275)
  charts/pipelines-library/templates/pipelines/cd/deploy-ansible.yaml
  charts/pipelines-library/templates/tasks/cd/deploy-ansible.yaml
  charts/pipelines-library/templates/triggers/cd/deploy-ansible.yaml
Labels: feature

#322 feat: Add support Bitbucket VSC for Go pipelines
  charts/common-library/Chart.yaml
  charts/common-library/README.md
  charts/common-library/templates/_common_bitbucket.yaml
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/pipelines/go/bitbucket-build-default.yaml
  charts/pipelines-library/templates/pipelines/go/bitbucket-build-edp.yaml
  charts/pipelines-library/templates/pipelines/go/bitbucket-review.yaml
  charts/pipelines-library/templates/triggers/bitbucket/triggerbinding-build.yaml
  charts/pipelines-library/templates/triggers/bitbucket/triggerbinding-review.yaml
  charts/pipelines-library/templates/triggers/bitbucket/tt-review.yaml
Labels: enhancement, feature

#327 fix: Use basic auth for Bitbucket Api request
  pkg/event_processor/bitbucket/bitbucket.go
Labels: bug

#328 chore: Update auth type for set-status task
  charts/pipelines-library/templates/tasks/bitbucket-set-status.yaml
Labels: dependencies, feature

#332 chore: Update alpine base image to v3.18.9 (#331)
  charts/pipelines-library/templates/tasks/check-helm-chart-name.yaml
  charts/pipelines-library/templates/tasks/codenarc.yaml
  charts/pipelines-library/templates/tasks/getversion/defaulttype/GetVersion.yaml
  charts/pipelines-library/templates/tasks/getversion/defaulttype/UpdateBuildNumberDotnet.yaml
  charts/pipelines-library/templates/tasks/getversion/defaulttype/UpdateBuildNumberGradle.yaml
  charts/pipelines-library/templates/tasks/getversion/defaulttype/UpdateBuildNumberPython.yaml
  charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberCsharp.yaml
  charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberDotnet.yaml
  charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberGradle.yaml
  charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberHelmChart.yaml
  charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberPython.yaml
  charts/pipelines-library/templates/tasks/kaniko.yaml
  charts/pipelines-library/templates/tasks/maven-get-module.yaml
  tests/e2e/bitbucket/01-assert.yaml
  tests/e2e/bitbucket/01-install.yaml
  tests/e2e/gerrit/01-assert.yaml
  tests/e2e/gerrit/01-install.yaml
  tests/e2e/github/01-assert.yaml
  tests/e2e/github/01-install.yaml
  tests/e2e/gitlab/01-assert.yaml
  tests/e2e/gitlab/01-install.yaml
Labels: enhancement

#335 fix: Update image for python pipelines
  charts/pipelines-library/templates/pipelines/python/bitbucket-build-default.yaml
  charts/pipelines-library/templates/pipelines/python/bitbucket-build-edp.yaml
  charts/pipelines-library/templates/pipelines/python/bitbucket-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/python/bitbucket-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/python/bitbucket-review-lib.yaml
  charts/pipelines-library/templates/pipelines/python/bitbucket-review.yaml
  charts/pipelines-library/templates/pipelines/python/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/python/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/python/gerrit-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/python/gerrit-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/python/gerrit-review-lib.yaml
  charts/pipelines-library/templates/pipelines/python/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/python/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/python/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/python/github-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/python/github-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/python/github-review-lib.yaml
  charts/pipelines-library/templates/pipelines/python/github-review.yaml
  charts/pipelines-library/templates/pipelines/python/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/python/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/python/gitlab-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/python/gitlab-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/python/gitlab-review-lib.yaml
  charts/pipelines-library/templates/pipelines/python/gitlab-review.yaml
Labels: bug

#308 feat: Pass env vars from ConfigMap for deploy task (#307)
  charts/pipelines-library/templates/tasks/cd/deploy-applicationset-cli.yaml
Labels: feature

#338 fix: Fix BitBucket commit url for Jira integration (#317)
  charts/pipelines-library/templates/tasks/push-to-jira.yaml
Labels: enhancement

#342 chore: Align tekton-cache version (#341)
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
Labels: enhancement

#343 chore: Update current development version (#341)
  CHANGELOG.md
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
Labels: enhancement

#346 chore: Update default terraform version to 1.5.7 (#345)
  charts/pipelines-library/templates/pipelines/infrastructure/bitbucket-build-default.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/bitbucket-build-edp.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/bitbucket-review.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/github-review.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/infrastructure/gitlab-review.yaml
  charts/pipelines-library/templates/pipelines/terraform/bitbucket-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/terraform/bitbucket-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/terraform/bitbucket-review-lib.yaml
  charts/pipelines-library/templates/pipelines/terraform/gerrit-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/terraform/gerrit-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/terraform/gerrit-review-lib.yaml
  charts/pipelines-library/templates/pipelines/terraform/github-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/terraform/github-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/terraform/github-review-lib.yaml
  charts/pipelines-library/templates/pipelines/terraform/gitlab-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/terraform/gitlab-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/terraform/gitlab-review-lib.yaml
  charts/pipelines-library/templates/tasks/terraform-check.yaml
Labels: enhancement

#347 chore: Update Pull Request Template (#56)
  pull_request_template.md
Labels: enhancement
