Repository epam/edp-tekton, pull requests merged in 2024-06, with the labels that each got.

#208 chore: Set default branch during project creation
  charts/pipelines-library/templates/tasks/sonar/sonarqube-dotnet.yaml
  charts/pipelines-library/templates/tasks/sonar/sonarqube-general.yaml
  charts/pipelines-library/templates/tasks/sonar/sonarqube-gradle.yaml
  charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml
Labels: enhancement

#206 chore: Update tekton pruner logic
  charts/pipelines-library/README.md
  charts/pipelines-library/scripts/tekton-prune.sh
  charts/pipelines-library/templates/resources/pruner/configmap.yaml
  charts/pipelines-library/templates/resources/pruner/cron-job.yaml
  charts/pipelines-library/templates/resources/pruner/rbac.yaml
  charts/pipelines-library/values.yaml
Labels: dependencies

#209 chore: Align argo diff for pruner
  charts/pipelines-library/templates/resources/pruner/configmap.yaml
Labels: bug

#210 chore: Align argo diff for pruner
  charts/pipelines-library/templates/resources/pruner/configmap.yaml
Labels: dependencies

#212 chore: Update current version
  charts/common-library/Chart.yaml
  charts/common-library/README.md
  charts/custom-pipelines/Chart.lock
  charts/custom-pipelines/Chart.yaml
  charts/custom-pipelines/README.md
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
  charts/tekton-cache/Chart.yaml
  charts/tekton-cache/README.md
Labels: enhancement

#213 chore: Update current version
  charts/custom-pipelines/Chart.yaml
  charts/custom-pipelines/README.md
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
Labels: enhancement
