Repository epam/edp-tekton, pull requests merged in 2024-05, with the labels that each got.

#181 chore: Update tekton-dashboard(#180)
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/dashboard/deployment.yaml
  charts/pipelines-library/values.yaml
Labels: enhancement

#185 fix: Make possible work with registry without registry parameter(#184)
  charts/pipelines-library/templates/tasks/helm-libraries/helm-push-lib.yaml
  charts/pipelines-library/templates/tasks/helm-push.yaml
Labels: bug

#183 chore: Bump to go 1.22
  .github/workflows/codecov.yaml
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  .golangci.yaml
  Makefile
  charts/custom-pipelines/templates/pipelines/_common_custom.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-build-cd-pipeline-operator-edp.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-build-edp-tekton-edp.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-build-keycloak-operator-edp.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-build-nexus-operator-edp.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-build-operator-edp.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-build-sam-go-app.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-build-sonar-operator-edp.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-cd-pipeline-operator.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-edp-common.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-edp-install.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-edp-tekton.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-keycloak-operator.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-nexus-operator.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-operator.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-sam-go-app.yaml
  charts/custom-pipelines/templates/pipelines/gerrit-review-sonar-operator.yaml
  charts/custom-pipelines/templates/pipelines/release/release-edp-install-component-operator.yaml
  charts/custom-pipelines/templates/pipelines/release/release-operators-headlamp-tekton.yaml
  charts/custom-pipelines/templates/tasks/CrdocsBuild.yaml
  charts/custom-pipelines/templates/tasks/integration-tests-keycloak.yaml
  charts/custom-pipelines/templates/tasks/integration-tests-nexus.yaml
  charts/custom-pipelines/templates/tasks/release/Build.yaml
  charts/custom-pipelines/templates/tasks/release/UpdateReleaseVersion.yaml
  charts/custom-pipelines/templates/tasks/release/ValidateReleaseBranch.yaml
  charts/pipelines-library/templates/pipelines/go/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/go/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/go/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/go/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/go/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/go/github-review.yaml
  charts/pipelines-library/templates/pipelines/go/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/go/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/go/gitlab-review.yaml
  charts/pipelines-library/templates/tasks/go.yaml
  go.mod
  go.sum
  kuttl-test.yaml
Labels: enhancement, go

#186 chore: Remove PR modify action for review pipeline (#187)
  charts/pipelines-library/templates/triggers/github/trigger-review.yaml
Labels: enhancement

#192 feat: Add quality gate for chart name alignment with codebase name(#191)
  charts/pipelines-library/templates/pipelines/helm/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/helm/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/helm/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/helm/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/helm/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/helm/github-review.yaml
  charts/pipelines-library/templates/pipelines/helm/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/helm/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/helm/gitlab-review.yaml
  charts/pipelines-library/templates/tasks/check-helm-chart-name.yaml
  charts/pipelines-library/tests/test_helm_pipelines.py
Labels: enhancement

#194 feat: Add lastCommitMessage to interceptor response
  cmd/interceptor/main.go
  pkg/event_processor/codebase.go
  pkg/event_processor/event.go
  pkg/event_processor/gerrit.go
  pkg/event_processor/gerrit/gerrit.go
  pkg/event_processor/gerrit/gerrit_test.go
  pkg/event_processor/gitlab.go
  pkg/event_processor/gitlab/gitlab.go
  pkg/event_processor/gitlab/gitlab_test.go
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/interceptor/edp_interceptor_test.go
Labels: enhancement, go

#200 fix: Set full stage name in autotests tekton task
  charts/pipelines-library/templates/tasks/autotest-cd-pipeline/init-autotests.yaml
Labels: bug

#202 chore: Bump Node image version to 18.20.3-alpine3.20
  charts/pipelines-library/templates/pipelines/_common_js_npm.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/github-review.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-review.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gerrit-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gerrit-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gerrit-review-lib.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/js/npm/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/github-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/github-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/github-review-lib.yaml
  charts/pipelines-library/templates/pipelines/js/npm/github-review.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gitlab-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gitlab-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gitlab-review-lib.yaml
  charts/pipelines-library/templates/pipelines/js/npm/gitlab-review.yaml
  charts/pipelines-library/templates/resources/cm-npm-settings.yaml
  charts/pipelines-library/templates/tasks/edp-npm.yaml
  charts/pipelines-library/templates/tasks/npm.yaml
Labels: bug

#196 fix: Resolve Version Conflict Between h11 and httpcore
  charts/pipelines-library/templates/pipelines/python/fastapi/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/python/fastapi/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/python/fastapi/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/python/fastapi/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/python/fastapi/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/python/fastapi/github-review.yaml
  charts/pipelines-library/templates/pipelines/python/fastapi/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/python/fastapi/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/python/fastapi/gitlab-review.yaml
Labels: bug
