Repository epam/edp-tekton, pull requests merged in 2024-04, with the labels that each got.

#161 chore: Migrate from gerrit to github pipelines
  .github/workflows/pr.yaml
  Makefile
  sonar-project.properties
  tests/e2e/gerrit/02-install.yaml
  tests/e2e/github/02-install.yaml
  tests/e2e/gitlab/02-install.yaml
Labels: dependencies

#167 chore: Add codeowners file to the repo
  CODEOWNERS
Labels: enhancement

#165 fix: Add lint config and remove cache from e2e
  .github/workflows/pr.yaml
  ct/chart_schema.yaml
  ct/ct.yaml
  ct/lintconf.yaml
  tests/e2e/gerrit/02-install.yaml
  tests/e2e/github/02-install.yaml
  tests/e2e/gitlab/02-install.yaml
Labels: bug

#163 chore: Adjust tekton pruner logic
  charts/pipelines-library/README.md
  charts/pipelines-library/values.yaml
Labels: dependencies

#170 feat: Exclude pipelinerun from resources displayed in argocd(#169)
  charts/custom-pipelines/templates/cd/deploy-custom.yaml
  charts/pipelines-library/templates/triggers/cd/deploy-with-autotests.yaml
  charts/pipelines-library/templates/triggers/cd/deploy.yaml
  charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
  charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
  charts/pipelines-library/templates/triggers/github/tt-build.yaml
  charts/pipelines-library/templates/triggers/github/tt-review.yaml
  charts/pipelines-library/templates/triggers/gitlab/tt-build.yaml
  charts/pipelines-library/templates/triggers/gitlab/tt-review.yaml
Labels: enhancement

#172 chore: Switch cache to recreate strategy type
  charts/tekton-cache/templates/deployment.yaml
Labels: enhancement
