Repository epam/edp-tekton, pull requests merged in 2024-07, with the labels that each got.

#214 chore: Update current version
  .github/workflows/pr.yaml
  CHANGELOG.md
  Makefile
  charts/custom-pipelines/Chart.yaml
  charts/custom-pipelines/README.md
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
Labels: enhancement

#231 fix: Fix commit-validate task to check only the first line
  charts/pipelines-library/templates/tasks/commit-validate.yaml
Labels: bug

#237 feat: Add pipelines tasks tests for new codebase ansible(#236)
  charts/pipelines-library/templates/pipelines/_common_python.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/gerrit-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/gerrit-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/gerrit-review-lib.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/github-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/github-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/github-review-lib.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/gitlab-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/gitlab-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/python/ansible/gitlab-review-lib.yaml
  charts/pipelines-library/templates/tasks/ansible.yaml
  charts/pipelines-library/tests/test_python_pipelines.py
Labels: enhancement

#235 feat: Add GitHub owners check configuration
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/triggers/github/trigger-review.yaml
  charts/pipelines-library/values.yaml
Labels: enhancement

#239 feat: Re-trigger Tekton Pipeline with /ok-to-test comment
  pkg/event_processor/event.go
  pkg/event_processor/gerrit/gerrit_test.go
  pkg/event_processor/gitlab/gitlab_test.go
  pkg/github/github_test.go
  pkg/interceptor/edp_interceptor.go
Labels: enhancement

#241 chore: Update github.com/epam/edp-codebase-operator dependency
  cmd/interceptor/main.go
  go.mod
  go.sum
  pkg/event_processor/codebase.go
  pkg/event_processor/event.go
  pkg/event_processor/gerrit/gerrit_test.go
  pkg/event_processor/gitlab/gitlab_test.go
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/interceptor/edp_interceptor.go
  pkg/interceptor/edp_interceptor_test.go
Labels: dependencies

#245 feat: Add clean pipelines for tekton
  charts/pipelines-library/templates/pipelines/cd/clean.yaml
  charts/pipelines-library/templates/tasks/cd/clean.yaml
  charts/pipelines-library/templates/triggers/cd/clean.yaml
Labels: enhancement
