Repository epam/edp-tekton, pull requests merged in 2024-08, with the labels that each got.

#249 chore: Update Gerrit Trigger Template for Remote Cluster Deployment
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
  charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
  charts/pipelines-library/tests/test_gerrit_integration.py
  charts/pipelines-library/values.yaml
Labels: enhancement

#247 chore: Make Tekton Dashboard quickLink deployment optional(#246)
  charts/pipelines-library/templates/resources/quicklinks/dashboard.yaml
Labels: enhancement

#254 feat: Update jira task Include GitCommit instead of Pipeline URL(#252)
  charts/common-library/Chart.yaml
  charts/common-library/README.md
  charts/common-library/templates/_common.yaml
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/tasks/push-to-jira.yaml
Labels: feature

#259 chore: Update KubeRocketCI names (#258)
  .github/workflows/release.yaml
  README.md
Labels: enhancement

#262 fix: Update parameter definition
  charts/pipelines-library/templates/triggers/gitlab/tt-build.yaml
Labels: bug

#261 feat: Add C make/cmake application pipelines
  charts/pipelines-library/templates/pipelines/_common_c.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/github-review.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/с/cmake/gitlab-review.yaml
  charts/pipelines-library/templates/pipelines/с/make/gerrit-build-default.yaml
  charts/pipelines-library/templates/pipelines/с/make/gerrit-build-edp.yaml
  charts/pipelines-library/templates/pipelines/с/make/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/с/make/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/с/make/github-build-edp.yaml
  charts/pipelines-library/templates/pipelines/с/make/github-review.yaml
  charts/pipelines-library/templates/pipelines/с/make/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/с/make/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/с/make/gitlab-review.yaml
  charts/pipelines-library/templates/tasks/edp-c.yaml
Labels: enhancement

#264 feat: Add dynamic pipeline name retrieval from CodebaseBranch spec
  go.mod
  go.sum
  pkg/github/github_test.go
  pkg/interceptor/edp_interceptor.go
  pkg/interceptor/edp_interceptor_test.go
Labels: enhancement

#267 chore: Disable Tekton dashboard deployments(#266)
  charts/pipelines-library/README.md
  charts/pipelines-library/values.yaml
  tests/e2e/gerrit/02-assert.yaml
  tests/e2e/github/02-assert.yaml
  tests/e2e/gitlab/02-assert.yaml
Labels: enhancement

#273 feat: Implement rpm build functionality
  charts/pipelines-library/templates/pipelines/rpm/github-build-default.yaml
  charts/pipelines-library/templates/pipelines/rpm/github-build-edp.yaml
  charts/pipelines-library/templates/tasks/edp-rpm.yaml
  charts/pipelines-library/templates/tasks/getversion/defaulttype/GetVersion.yaml
  charts/pipelines-library/templates/tasks/getversion/edptype/GetVersionEDP.yaml
Labels: enhancement

#274 fix: Align rpm-build argo diff
  charts/pipelines-library/templates/tasks/edp-rpm.yaml
Labels: bug

#269 docs: Replace EDP with KubeRocketCI in README md (#268)
  README.md
Labels: documentation

#280 feat: Add deploy pipeline with approve task(#279)
  charts/pipelines-library/templates/pipelines/cd/deploy-with-approve.yaml
  charts/pipelines-library/templates/triggers/cd/deploy-with-approve.yaml
Labels: enhancement
