Repository epam/edp-tekton, pull requests merged in 2025-01, with the labels that each got.

#394 fix: Update bitbucket vote parameters
  charts/common-library/Chart.yaml
  charts/common-library/README.md
  charts/common-library/templates/_common_bitbucket.yaml
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/pipelines/docker/kaniko/bitbucket-review.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-edp.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-review-lib.yaml
  charts/pipelines-library/templates/pipelines/helm/bitbucket-review-lib.yaml
  charts/pipelines-library/templates/pipelines/helm/bitbucket-review.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/bitbucket-review.yaml
  charts/pipelines-library/templates/pipelines/opa/bitbucket-review-lib.yaml
Labels: bug, invalid

#396 fix: Update bitbucket set-status task condition
  charts/common-library/Chart.yaml
  charts/common-library/README.md
  charts/common-library/templates/_common_bitbucket.yaml
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-build-default.yaml
  charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-build-edp.yaml
  charts/pipelines-library/templates/pipelines/autotests/maven/bitbucket-build-default.yaml
  charts/pipelines-library/templates/pipelines/autotests/maven/bitbucket-build-edp.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-edp.yaml
Labels: bug

#398 feat: Enable node selector for tekton pipelines
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/triggers/bitbucket/tt-build.yaml
  charts/pipelines-library/templates/triggers/bitbucket/tt-review.yaml
  charts/pipelines-library/templates/triggers/cd/clean.yaml
  charts/pipelines-library/templates/triggers/cd/deploy-ansible-awx.yaml
  charts/pipelines-library/templates/triggers/cd/deploy-ansible.yaml
  charts/pipelines-library/templates/triggers/cd/deploy-with-approve.yaml
  charts/pipelines-library/templates/triggers/cd/deploy-with-autotests.yaml
  charts/pipelines-library/templates/triggers/cd/deploy.yaml
  charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
  charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
  charts/pipelines-library/templates/triggers/github/tt-build.yaml
  charts/pipelines-library/templates/triggers/github/tt-review.yaml
  charts/pipelines-library/templates/triggers/gitlab/tt-build.yaml
  charts/pipelines-library/templates/triggers/gitlab/tt-review.yaml
  charts/pipelines-library/values.yaml
Labels: enhancement

#399 fix: Update gitlab set-status task condition
  charts/common-library/Chart.yaml
  charts/common-library/README.md
  charts/common-library/templates/_common_gitlab.yaml
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/autotests/maven/gitlab-build-default.yaml
  charts/pipelines-library/templates/pipelines/autotests/maven/gitlab-build-edp.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/gitlab-build-lib-default.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/gitlab-build-lib-edp.yaml
Labels: bug

#401 chore: Update current development version (#400)
  CHANGELOG.md
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
Labels: enhancement

#402 fix: Update Naming Convention for gradle cm
  charts/pipelines-library/templates/resources/cm-gradle-settings.yaml
Labels: bug

#405 chore: Align pipelineRun name patterns
  charts/pipelines-library/templates/triggers/bitbucket/tt-build.yaml
  charts/pipelines-library/templates/triggers/bitbucket/tt-review.yaml
  charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
  charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
  charts/pipelines-library/templates/triggers/github/tt-build.yaml
  charts/pipelines-library/templates/triggers/github/tt-review.yaml
  charts/pipelines-library/templates/triggers/gitlab/tt-build.yaml
  charts/pipelines-library/templates/triggers/gitlab/tt-review.yaml
Labels: enhancement

#408 fix: Update voting tasks
  charts/pipelines-library/templates/pipelines/docker/kaniko/github-review.yaml
  charts/pipelines-library/templates/pipelines/docker/kaniko/gitlab-review.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/github-review-lib.yaml
  charts/pipelines-library/templates/pipelines/helm-pipelines/gitlab-review-lib.yaml
  charts/pipelines-library/templates/pipelines/helm/github-review-lib.yaml
  charts/pipelines-library/templates/pipelines/helm/github-review.yaml
  charts/pipelines-library/templates/pipelines/helm/gitlab-review-lib.yaml
  charts/pipelines-library/templates/pipelines/helm/gitlab-review.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/github-review.yaml
  charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-review.yaml
  charts/pipelines-library/templates/pipelines/opa/github-review-lib.yaml
  charts/pipelines-library/templates/pipelines/opa/gitlab-review-lib.yaml
Labels: bug

#414 feat: Add APPLICATIONS_PAYLOAD results to deploy tasks
  charts/pipelines-library/templates/pipelines/cd/deploy-ansible-awx.yaml
  charts/pipelines-library/templates/pipelines/cd/deploy-ansible.yaml
  charts/pipelines-library/templates/pipelines/cd/deploy-with-approve.yaml
  charts/pipelines-library/templates/pipelines/cd/deploy-with-autotests.yaml
  charts/pipelines-library/templates/pipelines/cd/deploy.yaml
  charts/pipelines-library/templates/tasks/cd/deploy-ansible-awx.yaml
  charts/pipelines-library/templates/tasks/cd/deploy-ansible.yaml
  charts/pipelines-library/templates/tasks/cd/deploy-applicationset-cli.yaml
Labels: enhancement, feature

#416 chore: Add Build and Review pipelines for GitOps repo (#415)
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/pipelines/gitops/bitbucket-build.yaml
  charts/pipelines-library/templates/pipelines/gitops/bitbucket-review.yaml
  charts/pipelines-library/templates/pipelines/gitops/gerrit-build.yaml
  charts/pipelines-library/templates/pipelines/gitops/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/gitops/github-build.yaml
  charts/pipelines-library/templates/pipelines/gitops/github-review.yaml
  charts/pipelines-library/templates/pipelines/gitops/gitlab-build.yaml
  charts/pipelines-library/templates/pipelines/gitops/gitlab-review.yaml
  charts/pipelines-library/templates/tasks/gitops/yaml-lint.yaml
  charts/pipelines-library/values.yaml
  hack/images/images.txt
Labels: enhancement

#407 chore: Migrate Tekton Dashboard to cluster add-ons repo (#406)
  charts/pipelines-library/README.md
  charts/pipelines-library/templates/dashboard/_helpers.tpl
  charts/pipelines-library/templates/dashboard/cm-dashboard.yaml
  charts/pipelines-library/templates/dashboard/deployment.yaml
  charts/pipelines-library/templates/dashboard/ingress.yaml
  charts/pipelines-library/templates/dashboard/role-binding.yaml
  charts/pipelines-library/templates/dashboard/role.yaml
  charts/pipelines-library/templates/dashboard/route.yaml
  charts/pipelines-library/templates/dashboard/service-account.yaml
  charts/pipelines-library/templates/dashboard/service.yaml
  charts/pipelines-library/templates/resources/quicklinks/dashboard.yaml
  charts/pipelines-library/values.yaml
Labels: enhancement

#410 chore: Make QuickLink installation optional (#409)
  charts/pipelines-library/templates/resources/gitservers/quicklink.yaml
  charts/pipelines-library/tests/test_baseline.py
  charts/pipelines-library/tests/test_bitbucket_integration.py
  charts/pipelines-library/tests/test_gerrit_integration.py
  charts/pipelines-library/tests/test_github_integration.py
  charts/pipelines-library/tests/test_gitlab_integration.py
  charts/pipelines-library/values.yaml
  tests/e2e/values.yaml
Labels: enhancement

#418 chore: Rename parameter edp-gitops to krci-gitops
  charts/pipelines-library/templates/pipelines/gitops/bitbucket-build.yaml
  charts/pipelines-library/templates/pipelines/gitops/bitbucket-review.yaml
  charts/pipelines-library/templates/pipelines/gitops/gerrit-build.yaml
  charts/pipelines-library/templates/pipelines/gitops/gerrit-review.yaml
  charts/pipelines-library/templates/pipelines/gitops/github-build.yaml
  charts/pipelines-library/templates/pipelines/gitops/github-review.yaml
  charts/pipelines-library/templates/pipelines/gitops/gitlab-build.yaml
  charts/pipelines-library/templates/pipelines/gitops/gitlab-review.yaml
Labels: dependencies

#420 chore: Update current development version (#419)
  charts/common-library/Chart.yaml
  charts/common-library/README.md
  charts/pipelines-library/Chart.lock
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
Labels: enhancement

#421 chore: Update current development version (#419)
  CHANGELOG.md
  charts/pipelines-library/Chart.yaml
  charts/pipelines-library/README.md
Labels: enhancement
